InfoVote/info/urls.py
from django.urls import path

from info import views

app_name = 'info'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('search/', views.search_keyword, name='search'),
    path('details/<str:pk>/', views.ConstituencyDetail.as_view(), name='details'),
    path('profile/<int:pk>/', views.CandidateDetail.as_view(), name='profile'),
    path('results/<str:search_param>/<str:search_key>/', views.ResultsView.as_view(), name='results'),
    path('party/', views.PartyView.as_view(), name='party'),
]

InfoVote/infovote/urls.py
from django.contrib import admin
from django.urls import path, include

from infovote import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.info_redirect),
    path('info/', include('info.urls')),
]

InfoVote/info/models.py
from django.db import models


# Create your models here.


class Constituencies(models.Model):
    state = models.CharField(max_length=30)
    constituency = models.CharField(max_length=30)
    pincode = models.CharField(max_length=10, primary_key=True)
    upcoming_election_date = models.DateField()
    upcoming_election_type = models.CharField(max_length=30)

    def __str__(self):
        return self.pincode


class Candidates(models.Model):
    state = models.CharField(max_length=30)
    constituency = models.CharField(max_length=30)
    name = models.CharField(max_length=40)
    party = models.CharField(max_length=30)
    age = models.SmallIntegerField()
    address = models.TextField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    pincode = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=10, blank=True, null=True)
    educational_details = models.TextField(blank=True, null=True)
    assets = models.CharField(max_length=30, blank=True, null=True)
    liabilities = models.CharField(max_length=30, blank=True, null=True)
    criminal_cases = models.TextField(blank=True, null=True)
    election_type = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Party(models.Model):
    party = models.CharField(max_length=30)

    def __str__(self):
        return self.party


class State(models.Model):
    state = models.CharField(max_length=30)

    def __str__(self):
        return self.state


class Constituency_State(models.Model):
    constituency = models.CharField(max_length=30)
    state = models.CharField(max_length=30)

    def __str__(self):
        return self.constituency

InfoVote/info/views.py
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.views import generic
from .models import Constituencies, Candidates, State, Party, Constituency_State


# Create your views here.

class HomeView(generic.TemplateView):
    template_name = 'info/home.html'


class PartyView(generic.TemplateView):
    template_name = 'info/party.html'


class CandidateDetail(generic.DetailView):
    model = Candidates
    template_name = 'info/profile.html'
    context_object_name = 'candidate_object'


class ConstituencyDetail(generic.DetailView):
    model = Constituencies
    template_name = 'info/details.html'
    context_object_name = 'constituency_object'

    def get_context_data(self, **kwargs):
        details_context = super().get_context_data(**kwargs)
        current_constituency = self.get_object()
        candidate_list = Candidates.objects.filter(pincode=current_constituency.pincode,
                                                   constituency=current_constituency.constituency)
        details_context['candidate_list'] = candidate_list
        return details_context


class ResultsView(generic.ListView):
    template_name = 'info/results.html'
    context_object_name = 'results_list'

    def get_queryset(self):
        # print(self.kwargs)
        search_param = self.kwargs['search_param']
        search_key = self.kwargs['search_key']
        if search_param == 'pincode':
            return Constituencies.objects.filter(pincode__startswith=search_key)
        elif search_param == 'state':
            return State.objects.filter(state__startswith=search_key)
        elif search_param == 'constituency':
            return Constituencies.objects.filter(constituency__startswith=search_key)
        elif search_param == 'state-to-constituency':
            self.kwargs['search_param'] = 'constituency'
            search_key = search_key.replace('-',' ')
            return Constituency_State.objects.filter(state__icontains=search_key)
        elif search_param == 'party':
            return Party.objects.filter(party__startswith=search_key)
        elif search_param == 'constituency-to-candidate':
            self.kwargs['search_param'] = 'candidate'
            return Candidates.objects.filter(constituency__startswith=search_key)
        else:
            return Candidates.objects.filter(name__startswith=search_key)

    def get_context_data(self, *, object_list=None, **kwargs):
        results_context = super().get_context_data(object_list=object_list, **kwargs)
        results_context['search_param'] = self.kwargs['search_param']
        results_context['search_key'] = self.kwargs['search_key']
        return results_context


def search_keyword(request):
    search_param = request.POST['search_param']
    search_key = request.POST['search_key']
    print("search_param: ", search_param)
    print("search_key: ", search_key)
    return HttpResponseRedirect(
        reverse('info:results', args=(search_param, search_key,)))

InfoVote/infovote/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect


def info_redirect(request):
    return redirect('info/')

InfoVote/info/templates/info/details.html
<!DOCTYPE html>
{% load static %}
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<style>
.navbar {
      margin-bottom: 0;
      background-color: #31708f;
      z-index: 9999;
      border: 0;
      font-size: 14px !important;
      line-height: 1.42857143 !important;
      letter-spacing: 4px;
      border-radius: 0;
      font-family: Montserrat, sans-serif;
  }
  .navbar li a, .navbar .navbar-brand {
      color: #fff !important;
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
      color: #f4511e !important;
      background-color: #fff !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
      color: #fff !important;
  }
  footer .glyphicon {
      font-size: 20px;
      margin-bottom: 20px;
      color: #31708f;
  }
  .w3-bar-block a:hover{
      text-decoration: none;
  }
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>
<body class="w3-light-grey" id="myPage">

<!-- Top container -->

<div class="w3-bar w3-top w3-large" style="z-index:4;background-color:#31708f;">
  <span class="w3-bar-item w3-left w3-hide-medium w3-hide-small"><a class="w3-text-white" href="{% url 'info:home' %}">InfoVote</a></span>
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-text-white w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <span class="w3-bar-item w3-right"><a class="w3-text-white" href="{% url 'info:home' %}">Search again?</a></span>
</div>

<!--<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>

      <a class="navbar-brand" href="#myPage">InfoVote</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#about">ABOUT</a></li>
        <li><a href="#services">SERVICES</a></li>
        <li><a href="#contact">CONTACT</a></li>
      </ul>
    </div>
  </div>
</nav>-->

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img src="{% static 'details/bank.png' %}" class="w3-circle w3-margin-right" style="width:46px">
    </div>
    <div class="w3-col s8 w3-bar">
      <span><strong>{{ constituency_object.constituency }}</strong></span><br>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>
    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
    <a href="#" class="w3-bar-item w3-button w3-padding w3-blue"><i class="fa fa-users fa-fw"></i>  Overview</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-eye fa-fw"></i>  Views</a>
    <!--<a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i>  Traffic</a>-->
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullseye fa-fw"></i>  Geo</a>
    <!--<a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-diamond fa-fw"></i>  Orders</a>-->
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bell fa-fw"></i>  News</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bank fa-fw"></i>  General</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-history fa-fw"></i>  History</a>
    <!--<a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>-->
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">

  <!-- Header -->
  <header class="w3-container" style="padding-top:22px">
    <h5><b><i class="fa fa-dashboard"></i> Constituency : <strong>{{ constituency_object.constituency }}</strong></b></h5>
  </header>

  <div class="w3-row-padding w3-margin-bottom">
    <div class="w3-quarter">
      <div class="w3-container w3-red w3-padding-16">
        <div class="w3-left"><i class="fa fa-comment w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>{{ constituency_object.pincode }}</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Pincode</h4>
      </div>
    </div>
      <!--
    <div class="w3-quarter">
      <div class="w3-container w3-orange w3-padding-16">
        <div class="w3-left"><i class="fa fa-share-alt w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>23</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Shares</h4>
      </div>
    </div>
    -->
    <div class="w3-half">
      <div class="w3-container w3-teal w3-text-white w3-padding-16">
        <div class="w3-left"><i class="fa fa-users w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>{{ constituency_object.upcoming_election_type }}</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Upcoming Election type</h4>
      </div>
    </div>
    <div class="w3-quarter">
      <div class="w3-container w3-blue w3-padding-16">
        <div class="w3-left"><i class="fa fa-eye w3-xxxlarge"></i></div>
        <div class="w3-right">
          <h3>{{ constituency_object.upcoming_election_date }}</h3>
        </div>
        <div class="w3-clear"></div>
        <h4>Upcoming Elections date</h4>
      </div>
    </div>
  </div>

    <!--
  <div class="w3-panel">
    <div class="w3-row-padding" style="margin:0 -16px">
      <div class="w3-third">
        <h5>Regions</h5>
        <img src="{% static 'details/regions.gif' %}" style="width:100%" alt="Google Regional Map">
      </div>
      <div class="w3-twothird">
        <h5>Feeds</h5>
        <table class="w3-table w3-striped w3-white">
          <tr>
            <td><i class="fa fa-user w3-text-blue w3-large"></i></td>
            <td>New record, over 90 views.</td>
            <td><i>10 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-bell w3-text-red w3-large"></i></td>
            <td>Database error.</td>
            <td><i>15 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-users w3-text-yellow w3-large"></i></td>
            <td>New record, over 40 users.</td>
            <td><i>17 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-comment w3-text-red w3-large"></i></td>
            <td>New comments.</td>
            <td><i>25 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-bookmark w3-text-blue w3-large"></i></td>
            <td>Check transactions.</td>
            <td><i>28 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-laptop w3-text-red w3-large"></i></td>
            <td>CPU overload.</td>
            <td><i>35 mins</i></td>
          </tr>
          <tr>
            <td><i class="fa fa-share-alt w3-text-green w3-large"></i></td>
            <td>New shares.</td>
            <td><i>39 mins</i></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>General Stats</h5>
    <p>New Visitors</p>
    <div class="w3-grey">
      <div class="w3-container w3-center w3-padding w3-green" style="width:25%">+25%</div>
    </div>

    <p>New Users</p>
    <div class="w3-grey">
      <div class="w3-container w3-center w3-padding w3-orange" style="width:50%">50%</div>
    </div>

    <p>Bounce Rate</p>
    <div class="w3-grey">
      <div class="w3-container w3-center w3-padding w3-red" style="width:75%">75%</div>
    </div>
  </div>
  <hr>
  -->


  <div class="w3-container">
    <h5>List of candidates for upcoming elections</h5>
    <table class="w3-table w3-striped w3-bordered w3-border w3-hoverable w3-white">
        <tr>
            <th>Name</th>
            <th>State</th>
            <th>Party</th>
        </tr>
     {% for candidate in candidate_list %}
        <tr>
            <td> <a href="{% url 'info:profile' candidate.id %}"> {{ candidate.name }} </a> </td>
            <td>{{ candidate.state }}</td>
            <td>{{ candidate.party }}</td>
    {% endfor %}
        </tr>
    </table><br>
    <button class="w3-button w3-dark-grey"><i class="fa fa-arrow-left"></i> Past Elections</button>
      <button style="float: right;" class="w3-button w3-dark-grey">Future Elections <i class="fa fa-arrow-right"></i></button>
  </div>


    <hr>
  <div class="w3-container">
    <h5>Past elected candidates</h5>
    <ul class="w3-ul w3-card-4 w3-white">
      <li class="w3-padding-16">
        <img src="{% static 'details/avatar2.png' %}" class="w3-left w3-circle w3-margin-right" style="width:35px">
        <span class="w3-xlarge">Mike</span><br>
      </li>
      <li class="w3-padding-16">
        <img src="{% static 'details/avatar5.png' %}" class="w3-left w3-circle w3-margin-right" style="width:35px">
        <span class="w3-xlarge">Jill</span><br>
      </li>
      <li class="w3-padding-16">
        <img src="{% static 'details/avatar6.png' %}" class="w3-left w3-circle w3-margin-right" style="width:35px">
        <span class="w3-xlarge">Jane</span><br>
      </li>
    </ul>
  </div>
  <hr>

  <div class="w3-container">
    <h5>Recent Comments</h5>
    <div class="w3-row">
      <div class="w3-col m2 text-center">
        <img class="w3-circle" src="{% static 'details/avatar3.png' %}" style="width:96px;height:96px">
      </div>
      <div class="w3-col m10 w3-container">
        <h4>John <span class="w3-opacity w3-medium">Sep 29, 2014, 9:12 PM</span></h4>
        <p>Keep up the GREAT work! I am cheering for you!! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><br>
      </div>
    </div>

    <div class="w3-row">
      <div class="w3-col m2 text-center">
        <img class="w3-circle" src="{% static 'details/avatar1.png' %}" style="width:96px;height:96px">
      </div>
      <div class="w3-col m10 w3-container">
        <h4>Bo <span class="w3-opacity w3-medium">Sep 28, 2014, 10:15 PM</span></h4>
        <p>Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><br>
      </div>
    </div>
  </div>
  <br>
  <div class="w3-container w3-dark-grey w3-padding-32">
    <div class="w3-row">
      <div class="w3-container w3-third">
        <h5 class="w3-bottombar w3-border-green">Demographic</h5>
        <p>Language</p>
        <p>Country</p>
        <p>City</p>
      </div>
      <div class="w3-container w3-third">
        <h5 class="w3-bottombar w3-border-red">System</h5>
        <p>Browser</p>
        <p>OS</p>
        <p>More</p>
      </div>
      <div class="w3-container w3-third">
        <h5 class="w3-bottombar w3-border-orange">Target</h5>
        <p>Users</p>
        <p>Active</p>
        <p>Geo</p>
        <p>Interests</p>
      </div>
    </div>
  </div>

  <!-- Footer -->
    <br>
  <footer class="container-fluid text-center">
  <a href="#myPage" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p>Copyright &copy; InfoVote 2018</p>
</footer>

  <!-- End page content -->
</div>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
    if (mySidebar.style.display === 'block') {
        mySidebar.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidebar.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidebar with the close button
function w3_close() {
    mySidebar.style.display = "none";
    overlayBg.style.display = "none";
}
</script>

</body>
</html>

InfoVote/info/templates/info/results.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'results/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'results/css/blog-home.css' %}" rel="stylesheet">


  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color:#31708f;">
      <div class="container">
        <a class="navbar-brand" href="{% url 'info:home' %}" style="font-family: Montserrat, sans-serif;letter-spacing: 4px;">InfoVote</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#" style="font-family: Montserrat, sans-serif;letter-spacing: 4px;">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" style="font-family: Montserrat, sans-serif;letter-spacing: 4px;">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" style="font-family: Montserrat, sans-serif;letter-spacing: 4px;">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="my-4">Results for {{search_param}} :
            <small>{{ search_key }}</small>
          </h1>


          <!-- Blog Post -->
          {% if not results_list|length %}
                  <strong>No results found</strong><br><br><br>
          {% elif search_param == 'pincode' %}
            {% for object in results_list %}
              <div class="card mb-4">
                <!--<img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">-->
                <div class="card-body">
                  <h2 class="card-title">{{ object.constituency }}</h2>
                  <p class="card-text">This constituency is present in {{ object.state }} state and is responsible for area with pincode: {{ object.pincode }}</p>
                  <a href="{% url 'info:details' object.pincode %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                  Updated on January 1, 2018 by
                  <a href="{% url 'info:home' %}">InfoVote</a>
                </div>
              </div>
            {% endfor %}
          {% elif search_param == 'state' %}
            {% for object in results_list %}
              <div class="card mb-4">
                <!--<img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">-->
                <div class="card-body">
                  <h2 class="card-title">{{ object.state }}</h2>
                  <p class="card-text">Some text about the state</p>
                  <a href="{% url 'info:results' 'state-to-constituency' object.state|slugify %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                  Updated on January 1, 2018 by
                  <a href="{% url 'info:home' %}">InfoVote</a>
                </div>
              </div>
            {% endfor %}
          {% elif search_param == 'constituency' %}
            {% for object in results_list %}
              <div class="card mb-4">
                <!--<img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">-->
                <div class="card-body">
                  <h2 class="card-title">{{ object.constituency }}</h2>
                  <p class="card-text">Some text about the constituency</p>
                  <a href="{% url 'info:results' 'constituency-to-candidate' object.constituency %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                  Updated on January 1, 2018 by
                  <a href="{% url 'info:home' %}">InfoVote</a>
                </div>
              </div>
            {% endfor %}
          {% elif search_param == 'party' %}
            {% for object in results_list %}
              <div class="card mb-4">
                <!--<img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">-->
                <div class="card-body">
                  <h2 class="card-title">{{ object.party }}</h2>
                  <p class="card-text">Some text about the party</p>
                  <a href="{% url 'info:party' %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                  Updated on January 1, 2018 by
                  <a href="{% url 'info:home' %}">InfoVote</a>
                </div>
              </div>
            {% endfor %}
          {% else %}
            {% for object in results_list %}
              <div class="card mb-4">
                <!--<img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">-->
                <div class="card-body">
                  <h2 class="card-title">{{ object.name }}</h2>
                    <p class="card-text">This candidate is member of <a href="{% url 'info:details' object.pincode %}">{{ object.constituency }}</a> constituency and represents <a href="{% url 'info:party' %}">{{ object.party }}</a></p>
                  <a href="{% url 'info:profile' object.id %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
                <div class="card-footer text-muted">
                  Updated on January 1, 2018 by
                  <a href="{% url 'info:home' %}">InfoVote</a>
                </div>
              </div>
            {% endfor %}
          {% endif %}

          <!-- Pagination -->
          <ul class="pagination justify-content-center mb-4">
            <li class="page-item disabled">
              <a class="page-link" href="#">&larr; Prev</a>
            </li>
            <li class="page-item disabled">
              <a class="page-link" href="#">Next &rarr;</a>
            </li>
          </ul>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <a href="{% url 'info:home' %}" class="text-white"><button class="btn btn-secondary" type="button">Go</button></a>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Web Design</a>
                    </li>
                    <li>
                      <a href="#">HTML</a>
                    </li>
                    <li>
                      <a href="#">Freebies</a>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">JavaScript</a>
                    </li>
                    <li>
                      <a href="#">CSS</a>
                    </li>
                    <li>
                      <a href="#">Tutorials</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5" style="background-color:#31708f;">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; InfoVote 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'results/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'results/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>